In [127]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
import plotly.express as px
%matplotlib inline

In [128]:
df=pd.read_csv('cardekho_dataset.csv',index_col=0)
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [129]:
df.drop('car_name',axis=1,inplace=True)
df.head()

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [130]:
df.isnull().sum()

brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [131]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [132]:
df.dtypes

brand                 object
model                 object
vehicle_age            int64
km_driven              int64
seller_type           object
fuel_type             object
transmission_type     object
mileage              float64
engine                 int64
max_power            float64
seats                  int64
selling_price          int64
dtype: object

In [133]:
num_features=[i for i in df.columns if df[i].dtype!='O']
print('num_features:',len(num_features))
print(num_features)

num_features: 7
['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']

In [134]:
cat_features=[i for i in df.columns if df[i].dtype=='O']
print('categorical features',len(cat_features))
print(cat_features)

categorical features 5
['brand', 'model', 'seller_type', 'fuel_type', 'transmission_type']

In [135]:
discrete_features=[i for i in num_features if len(df[i].unique())<=25]
print('Discrete Features',len(discrete_features))

Discrete Features 2

In [136]:
cont_features=[i for i  in num_features if i not in discrete_features]
print('continous feature',len(cont_features))

continous feature 5

In [137]:
##independent feature and depent features

df = df.drop_duplicates().reset_index(drop=True)

from sklearn.model_selection import train_test_split
x=df.drop(['selling_price'],axis=1)
y=df['selling_price']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [138]:
df

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...
15239,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15240,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15241,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15242,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15243,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [139]:
x.head()

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [140]:
y.head()

0    120000
1    550000
2    215000
3    226000
4    570000
Name: selling_price, dtype: int64

Feature encoding

one hot encoding

In [141]:
len(df['model'].unique())

120

In [142]:
df['model'].value_counts()

model
i20             898
Swift Dzire     875
Swift           774
Alto            768
City            750
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [143]:
print("Brand:", df['brand'].nunique())
print("Model:", df['model'].nunique())

Brand: 32
Model: 120

In [144]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_features=numeric_features = ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']


numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop="first",handle_unknown='ignore')



preprocessor=ColumnTransformer(

    [
        ("one hot encoder",oh_transformer,cat_features),
        ("standard scaler",numeric_transformer,numeric_features)
    ],remainder='passthrough'
)

In [145]:
x.head()

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [146]:
pd.DataFrame(x)

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...,...
15239,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15240,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15241,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15242,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15243,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [147]:
x_train_processed=preprocessor.fit_transform(x_train)
x_test_processed=preprocessor.transform(x_test)

d:\PYTHON\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [148]:
feature_names = preprocessor.get_feature_names_out()

print(feature_names)
print("Number of features:", len(feature_names))

['one hot encoder__brand_BMW' 'one hot encoder__brand_Bentley'
 'one hot encoder__brand_Datsun' 'one hot encoder__brand_Ferrari'
 'one hot encoder__brand_Force' 'one hot encoder__brand_Ford'
 'one hot encoder__brand_Honda' 'one hot encoder__brand_Hyundai'
 'one hot encoder__brand_ISUZU' 'one hot encoder__brand_Isuzu'
 'one hot encoder__brand_Jaguar' 'one hot encoder__brand_Jeep'
 'one hot encoder__brand_Kia' 'one hot encoder__brand_Land Rover'
 'one hot encoder__brand_Lexus' 'one hot encoder__brand_MG'
 'one hot encoder__brand_Mahindra' 'one hot encoder__brand_Maruti'
 'one hot encoder__brand_Maserati' 'one hot encoder__brand_Mercedes-AMG'
 'one hot encoder__brand_Mercedes-Benz' 'one hot encoder__brand_Mini'
 'one hot encoder__brand_Nissan' 'one hot encoder__brand_Porsche'
 'one hot encoder__brand_Renault' 'one hot encoder__brand_Skoda'
 'one hot encoder__brand_Tata' 'one hot encoder__brand_Toyota'
 'one hot encoder__brand_Volkswagen' 'one hot encoder__brand_Volvo'
 'one hot encoder__model_5' 'one hot encoder__model_6'
 'one hot encoder__model_7' 'one hot encoder__model_A4'
 'one hot encoder__model_A6' 'one hot encoder__model_A8'
 'one hot encoder__model_Alto' 'one hot encoder__model_Altroz'
 'one hot encoder__model_Amaze' 'one hot encoder__model_Aspire'
 'one hot encoder__model_Aura' 'one hot encoder__model_Baleno'
 'one hot encoder__model_Bolero' 'one hot encoder__model_C'
 'one hot encoder__model_C-Class' 'one hot encoder__model_CLS'
 'one hot encoder__model_CR' 'one hot encoder__model_CR-V'
 'one hot encoder__model_Camry' 'one hot encoder__model_Carnival'
 'one hot encoder__model_Cayenne' 'one hot encoder__model_Celerio'
 'one hot encoder__model_Ciaz' 'one hot encoder__model_City'
 'one hot encoder__model_Civic' 'one hot encoder__model_Compass'
 'one hot encoder__model_Continental' 'one hot encoder__model_Cooper'
 'one hot encoder__model_Creta' 'one hot encoder__model_D-Max'
 'one hot encoder__model_Duster' 'one hot encoder__model_Dzire LXI'
 'one hot encoder__model_Dzire VXI' 'one hot encoder__model_Dzire ZXI'
 'one hot encoder__model_E-Class' 'one hot encoder__model_ES'
 'one hot encoder__model_Ecosport' 'one hot encoder__model_Eeco'
 'one hot encoder__model_Elantra' 'one hot encoder__model_Endeavour'
 'one hot encoder__model_Ertiga' 'one hot encoder__model_F-PACE'
 'one hot encoder__model_Figo' 'one hot encoder__model_Fortuner'
 'one hot encoder__model_Freestyle' 'one hot encoder__model_GL-Class'
 'one hot encoder__model_GLS' 'one hot encoder__model_GO'
 'one hot encoder__model_GTC4Lusso' 'one hot encoder__model_Ghibli'
 'one hot encoder__model_Glanza' 'one hot encoder__model_Grand'
 'one hot encoder__model_Gurkha' 'one hot encoder__model_Harrier'
 'one hot encoder__model_Hector' 'one hot encoder__model_Hexa'
 'one hot encoder__model_Ignis' 'one hot encoder__model_Innova'
 'one hot encoder__model_Jazz' 'one hot encoder__model_KUV'
 'one hot encoder__model_KUV100' 'one hot encoder__model_KWID'
 'one hot encoder__model_Kicks' 'one hot encoder__model_MUX'
 'one hot encoder__model_Macan' 'one hot encoder__model_Marazzo'
 'one hot encoder__model_Nexon' 'one hot encoder__model_Octavia'
 'one hot encoder__model_Panamera' 'one hot encoder__model_Polo'
 'one hot encoder__model_Q7' 'one hot encoder__model_RX'
 'one hot encoder__model_Rapid' 'one hot encoder__model_RediGO'
 'one hot encoder__model_Rover' 'one hot encoder__model_S-Class'
 'one hot encoder__model_S-Presso' 'one hot encoder__model_S90'
 'one hot encoder__model_Safari' 'one hot encoder__model_Santro'
 'one hot encoder__model_Scorpio' 'one hot encoder__model_Seltos'
 'one hot encoder__model_Superb' 'one hot encoder__model_Swift'
 'one hot encoder__model_Swift Dzire' 'one hot encoder__model_Thar'
 'one hot encoder__model_Tiago' 'one hot encoder__model_Tigor'
 'one hot encoder__model_Triber' 'one hot encoder__model_Tucson'
 'one hot encoder__model_Vento' 'one hot encoder__model_Venue'
 'one hot encoder__model_Verna' 'one hot encoder__model_Vitara'
 'one hot encoder__model_WR-V' 'one hot encoder__model_Wagon R'
 'one hot encoder__model_Wrangler' 'one hot encoder__model_X-Trail'
 'one hot encoder__model_X1' 'one hot encoder__model_X3'
 'one hot encoder__model_X4' 'one hot encoder__model_X5'
 'one hot encoder__model_XC' 'one hot encoder__model_XC60'
 'one hot encoder__model_XC90' 'one hot encoder__model_XE'
 'one hot encoder__model_XF' 'one hot encoder__model_XL6'
 'one hot encoder__model_XUV300' 'one hot encoder__model_XUV500'
 'one hot encoder__model_Yaris' 'one hot encoder__model_Z4'
 'one hot encoder__model_i10' 'one hot encoder__model_i20'
 'one hot encoder__model_redi-GO'
 'one hot encoder__seller_type_Individual'
 'one hot encoder__seller_type_Trustmark Dealer'
 'one hot encoder__fuel_type_Diesel' 'one hot encoder__fuel_type_Electric'
 'one hot encoder__fuel_type_LPG' 'one hot encoder__fuel_type_Petrol'
 'one hot encoder__transmission_type_Manual'
 'standard scaler__vehicle_age' 'standard scaler__km_driven'
 'standard scaler__mileage' 'standard scaler__engine'
 'standard scaler__max_power' 'standard scaler__seats']
Number of features: 158

In [149]:


x_train_encoded = pd.DataFrame(
    x_train_processed.toarray(),
    columns=feature_names,
    index=x_train.index
)

print(x_train_encoded.head())

       one hot encoder__brand_BMW  one hot encoder__brand_Bentley  \
275                           0.0                             0.0
9063                          0.0                             0.0
13342                         0.0                             0.0
10678                         0.0                             0.0
1272                          0.0                             0.0

       one hot encoder__brand_Datsun  one hot encoder__brand_Ferrari  \
275                              0.0                             0.0
9063                             0.0                             0.0
13342                            0.0                             0.0
10678                            0.0                             0.0
1272                             0.0                             0.0

       one hot encoder__brand_Force  one hot encoder__brand_Ford  \
275                             0.0                          0.0
9063                            0.0                          0.0
13342                           0.0                          0.0
10678                           0.0                          0.0
1272                            0.0                          0.0

       one hot encoder__brand_Honda  one hot encoder__brand_Hyundai  \
275                             1.0                             0.0
9063                            1.0                             0.0
13342                           0.0                             0.0
10678                           1.0                             0.0
1272                            0.0                             0.0

       one hot encoder__brand_ISUZU  one hot encoder__brand_Isuzu  ...  \
275                             0.0                           0.0  ...
9063                            0.0                           0.0  ...
13342                           0.0                           0.0  ...
10678                           0.0                           0.0  ...
1272                            0.0                           0.0  ...

       one hot encoder__fuel_type_Electric  one hot encoder__fuel_type_LPG  \
275                                    0.0                             0.0
9063                                   0.0                             0.0
13342                                  0.0                             0.0
10678                                  0.0                             0.0
1272                                   0.0                             0.0

       one hot encoder__fuel_type_Petrol  \
275                                  1.0
9063                                 1.0
13342                                1.0
10678                                1.0
1272                                 0.0

       one hot encoder__transmission_type_Manual  \
275                                          1.0
9063                                         1.0
13342                                        1.0
10678                                        1.0
1272                                         1.0

       standard scaler__vehicle_age  standard scaler__km_driven  \
275                       -0.017022                    0.089908
9063                       2.295905                    0.424970
13342                     -1.338695                   -0.757455
10678                      1.304650                   -0.121933
1272                      -1.338695                   -0.592690

       standard scaler__mileage  standard scaler__engine  \
275                   -0.407599                -0.544145
9063                  -1.491689                 0.613224
13342                  1.319717                -1.312515
10678                 -0.648508                 0.031651
1272                  -0.899054                 2.007458

       standard scaler__max_power  standard scaler__seats
275                     -0.317313               -0.399344
9063                     0.686340               -0.399344
13342                   -1.091494               -0.399344
10678                    0.408191               -0.399344
1272                    -0.866657                4.595955

[5 rows x 158 columns]

In [150]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics  import r2_score,mean_absolute_error,mean_squared_error

In [151]:
# ##create function to evaluate model
# def evaluate_model(true,predicted):
#     mae=mean_absolute_error(true,predicted)
#     mse=mean_squared_error(true,predicted)
#     rmse=mean_squared_error(true,predicted)
#     r2_square=r2_score(true,predicted)
#     return mae,mse,r2_score,rmse

Model Training Begins

In [152]:


models={
    "Linear Regressor":LinearRegression(),
    "Lasso Regressiion":Lasso(),
    "Ridge Regression":Ridge(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeRegressor(),
    "Random Forest Regressor":RandomForestRegressor()
}


for i in range (len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train_processed,y_train)

    #make predictions

    y_train_pred=model.predict(x_train_processed)
    y_test_pred=model.predict(x_test_processed)

    model_train_mse = mean_squared_error(y_train, y_train_pred)
    model_train_rmse = np.sqrt(model_train_mse)
    model_train_mae = mean_absolute_error(y_train, y_train_pred)
    model_train_r2_square=r2_score(y_train, y_train_pred)


    model_test_mse = mean_squared_error(y_test, y_test_pred)
    model_test_rmse = np.sqrt(model_test_mse)
    model_test_mae = mean_absolute_error(y_test, y_test_pred)
    model_test_r2_square=r2_score(y_test, y_test_pred)


    print(list(models.keys())[i])

    print('Model performance for Training Set')
    print('Root mean Squared Error: {:4f}'.format(model_train_rmse))
    print("Mean Absolute Error: {:4f}".format(model_train_mae))
    print("Mean Squared Error : {:4f}".format(model_train_mse))
    print("r2 Square:{:4f}".format(model_train_r2_square))


    print('-----------------------------------------------------------------')
    print('Model performance for Test Set')
    print('Root mean Squared Error: {:4f}'.format(model_test_rmse))
    print("Mean Absolute Error: {:4f}".format(model_test_mae))
    print("Mean Squared Error : {:4f}".format(model_test_mse))
    print("r2 Square:{:4f}".format(model_test_r2_square))

    print("="*35)
    print('\n')

Linear Regressor
Model performance for Training Set
Root mean Squared Error: 358982.106301
Mean Absolute Error: 172294.348936
Mean Squared Error : 128868152644.301193
r2 Square:0.840745
-----------------------------------------------------------------
Model performance for Test Set
Root mean Squared Error: 465968.924122
Mean Absolute Error: 175000.888502
Mean Squared Error : 217127038247.073975
r2 Square:0.719384
===================================

d:\PYTHON\venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.254e+14, tolerance: 9.252e+11
  model = cd_fast.sparse_enet_coordinate_descent(

Lasso Regressiion
Model performance for Training Set
Root mean Squared Error: 358982.701362
Mean Absolute Error: 172304.306368
Mean Squared Error : 128868579876.922852
r2 Square:0.840744
-----------------------------------------------------------------
Model performance for Test Set
Root mean Squared Error: 485407.272904
Mean Absolute Error: 175347.253936
Mean Squared Error : 235620220588.372314
r2 Square:0.695484
===================================


Ridge Regression
Model performance for Training Set
Root mean Squared Error: 378069.803420
Mean Absolute Error: 180660.756559
Mean Squared Error : 142936776258.143982
r2 Square:0.823359
-----------------------------------------------------------------
Model performance for Test Set
Root mean Squared Error: 454705.604081
Mean Absolute Error: 182081.543004
Mean Squared Error : 206757186382.692688
r2 Square:0.732786
===================================


K-Neighbors Regressor
Model performance for Training Set
Root mean Squared Error: 283914.612366
Mean Absolute Error: 85912.050643
Mean Squared Error : 80607507114.657135
r2 Square:0.900385
-----------------------------------------------------------------
Model performance for Test Set
Root mean Squared Error: 308140.581073
Mean Absolute Error: 104327.361585
Mean Squared Error : 94950617704.178696
r2 Square:0.877285
===================================


Decision Tree
Model performance for Training Set
Root mean Squared Error: 19327.999276
Mean Absolute Error: 4588.471967
Mean Squared Error : 373571556.022041
r2 Square:0.999538
-----------------------------------------------------------------
Model performance for Test Set
Root mean Squared Error: 328655.891669
Mean Absolute Error: 125712.245255
Mean Squared Error : 108014695128.429413
r2 Square:0.860401
===================================


Random Forest Regressor
Model performance for Training Set
Root mean Squared Error: 138579.802039
Mean Absolute Error: 39170.923395
Mean Squared Error : 19204361533.302979
r2 Square:0.976267
-----------------------------------------------------------------
Model performance for Test Set
Root mean Squared Error: 292084.196329
Mean Absolute Error: 101781.862415
Mean Squared Error : 85313177745.305496
r2 Square:0.889741
===================================

In [153]:
print(x.columns.tolist())

['brand', 'model', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power', 'seats']

In [154]:
print(
    df.corr(numeric_only=True)['selling_price']
      .sort_values(ascending=False)
)

selling_price    1.000000
max_power        0.751058
engine           0.585713
seats            0.115299
km_driven       -0.079548
vehicle_age     -0.241228
mileage         -0.305128
Name: selling_price, dtype: float64

In [155]:
print(df.duplicated().sum())

print(x.columns.tolist())

print(df.corr(numeric_only=True)['selling_price'].sort_values(ascending=False))

print(y_train.describe())
print(y_test.describe())

0
['brand', 'model', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power', 'seats']
selling_price    1.000000
max_power        0.751058
engine           0.585713
seats            0.115299
km_driven       -0.079548
vehicle_age     -0.241228
mileage         -0.305128
Name: selling_price, dtype: float64
count    1.143300e+04
mean     7.702291e+05
std      8.995909e+05
min      4.000000e+04
25%      3.850000e+05
50%      5.500000e+05
75%      8.100000e+05
max      3.950000e+07
Name: selling_price, dtype: float64
count    3.811000e+03
mean     7.881186e+05
std      8.797473e+05
min      6.000000e+04
25%      3.850000e+05
50%      5.760000e+05
75%      8.400000e+05
max      2.420000e+07
Name: selling_price, dtype: float64

In [157]:
results = x_test.copy()

results['Actual'] = y_test
results['Predicted'] = y_test_pred

results['Error'] = results['Actual'] - results['Predicted']
results['Absolute_Error'] = abs(results['Error'])

print(
    results.sort_values(
        'Absolute_Error',
        ascending=False
    ).head(20)
)

               brand        model  vehicle_age  km_driven seller_type  \
10870    Rolls-Royce        Ghost            4       5000  Individual
9954         Bentley  Continental            9      37500      Dealer
3482      Land Rover        Rover            8      75000      Dealer
1740      Volkswagen         Polo            3      18523      Dealer
14393          Lexus           NX            3       7622      Dealer
14023          Lexus           RX            5      17272      Dealer
3087             BMW            7            3      50000  Individual
13242          Honda         CR-V            2      20000  Individual
970             Audi           A6            1       3000      Dealer
284       Land Rover        Rover            3      13000      Dealer
6174   Mercedes-Benz      E-Class            4       1198      Dealer
2746             BMW            5            5      27000      Dealer
111              BMW            5            5      63000      Dealer
8480           Lexus           NX            3      44000      Dealer
6621   Mercedes-Benz          CLS            5      10000      Dealer
7447           Honda           CR            8      55000      Dealer
3355             BMW           X5           13      61000      Dealer
12013     Land Rover        Rover            7      52000      Dealer
3774             BMW            7            4      21119      Dealer
8161             BMW            7            6      30000  Individual

      fuel_type transmission_type  mileage  engine  max_power  seats  \
10870    Petrol         Automatic    10.20    6592     563.00      4
9954     Petrol         Automatic     6.00    5998     600.00      5
3482     Diesel         Automatic    13.33    2993     244.10      5
1740     Petrol         Automatic    17.21    1798     189.00      4
14393    Petrol         Automatic    18.32    2499     194.30      5
14023    Petrol         Automatic    18.80    3456     259.00      5
3087     Diesel         Automatic    16.77    2993     261.49      5
13242    Diesel         Automatic    19.50    1597     118.30      7
970      Petrol         Automatic    17.01    1984     241.30      5
284      Petrol         Automatic    12.19    1997     237.36      4
6174     Petrol         Automatic    12.00    1991     184.00      5
2746     Diesel         Automatic    14.69    2993     258.00      5
111      Diesel         Automatic    18.59    2993     261.49      5
8480     Petrol         Automatic    18.32    2499     194.30      5
6621     Diesel         Automatic    19.40    2143     204.00      4
7447     Petrol         Automatic    12.00    2354     187.40      5
3355     Diesel         Automatic    11.00    2993     235.00      5
12013    Diesel         Automatic    12.70    2179     187.70      5
3774     Diesel         Automatic    16.46    2993     258.00      5
8161     Diesel         Automatic    16.46    2993     258.00      5

         Actual     Predicted         Error  Absolute_Error
10870  24200000  1.248345e+07  1.171655e+07    1.171655e+07
9954    5200000  1.040913e+07 -5.209130e+06    5.209130e+06
3482    7800000  2.934116e+06  4.865884e+06    4.865884e+06
1740     875000  3.718880e+06 -2.843880e+06    2.843880e+06
14393   6400000  3.632390e+06  2.767610e+06    2.767610e+06
14023   8000000  5.425235e+06  2.574765e+06    2.574765e+06
3087    8500000  6.161233e+06  2.338767e+06    2.338767e+06
13242   3100000  1.254814e+06  1.845186e+06    1.845186e+06
970     4600000  6.342700e+06 -1.742700e+06    1.742700e+06
284     7000000  5.279780e+06  1.720220e+06    1.720220e+06
6174    5743000  4.041550e+06  1.701450e+06    1.701450e+06
2746    3200000  4.759067e+06 -1.559067e+06    1.559067e+06
111     2600000  4.073590e+06 -1.473590e+06    1.473590e+06
8480    4500000  3.181057e+06  1.318943e+06    1.318943e+06
6621    4900000  3.614690e+06  1.285310e+06    1.285310e+06
7447     890000  2.154790e+06 -1.264790e+06    1.264790e+06
3355    1975000  7.255600e+05  1.249440e+06    1.249440e+06
12013   2400000  3.594140e+06 -1.194140e+06    1.194140e+06
3774    7500000  6.312897e+06  1.187103e+06    1.187103e+06
8161    5500000  4.373160e+06  1.126840e+06    1.126840e+06

In [158]:
#hyper parameter tunning

from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 15, 20, 25, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4, 8],
    'max_features': [1.0, 'sqrt', 'log2']
}



rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

In [159]:
random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=30,
    scoring='neg_root_mean_squared_error',
    cv=3,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

In [160]:
random_search.fit(x_train_processed, y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

RandomizedSearchCV(cv=3,
                   estimator=RandomForestRegressor(n_jobs=-1, random_state=42),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'max_depth': [None, 10, 15, 20, 25, 30],
                                        'max_features': [1.0, 'sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4, 8],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='neg_root_mean_squared_error',
                   verbose=2)

In [161]:
print("Best Parameters:")
print(random_search.best_params_)

print("Best CV Score:")
print(random_search.best_score_)

Best Parameters:
{'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 1.0, 'max_depth': 30}
Best CV Score:
-310035.62085630355

In [162]:
best_rf = random_search.best_estimator_

y_test_pred = best_rf.predict(x_test_processed)
y_train_pred = best_rf.predict(x_train_processed)

In [163]:
train_mae = mean_absolute_error(y_train, y_train_pred)
train_mse = mean_squared_error(y_train, y_train_pred)
train_rmse = np.sqrt(train_mse)
train_r2 = r2_score(y_train, y_train_pred)

print("\nTraining MAE :", train_mae)
print("Training MSE :", train_mse)
print("Training RMSE:", train_rmse)
print("Training R2  :", train_r2)



# Test
test_mae = mean_absolute_error(y_test, y_test_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_rmse = np.sqrt(test_mse)
test_r2 = r2_score(y_test, y_test_pred)

print("Test MAE :", test_mae)
print("Test MSE :", test_mse)
print("Test RMSE:", test_rmse)
print("Test R2  :", test_r2)

Training MAE : 38819.68773941022
Training MSE : 13836408887.942854
Training RMSE: 117628.26568449802
Training R2  : 0.9829009775492558
Test MAE : 101737.96486522768
Test MSE : 83593354822.44081
Test RMSE: 289125.1542540718
Test R2  : 0.8919636572552931

Saving the best model

In [165]:
#  Save model + preprocessor
import pickle

with open("car_price_model.pkl", "wb") as file:
    pickle.dump(best_rf, file)

with open("preprocessor.pkl", "wb") as file:
    pickle.dump(preprocessor, file)

print("Model and preprocessor saved successfully!")

Model and preprocessor saved successfully!